# vim:ft=kitty

## name:     Kanagawa Wave
## author:   Tommaso Laurenzi
## license:  MIT
## upstream: https://github.com/rebelot/kanagawa.nvim/

# The basic colors
foreground              #DCD7BA
background              #000000
selection_foreground    #C8C093
selection_background    #2D4F67

# Cursor colors
cursor                  #C8C093
cursor_text_color       #1F1F28

# Scrollbar colors
scrollbar_handle_color  #54546D
scrollbar_track_color   #2A2A37

# URL color when hovering with mouse
url_color               #72A7BC

# Kitty window border colors
active_border_color     none
inactive_border_color   #54546D
bell_border_color       #E6C384

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #16161D
active_tab_background   #7E9CD8
inactive_tab_foreground #DCD7BA
inactive_tab_background #2A2A37
tab_bar_background      none

# Colors for marks (marked text in the terminal)
mark1_foreground #1F1F28
mark1_background #7E9CD8
mark2_foreground #1F1F28
mark2_background #957FB8
mark3_foreground #1F1F28
mark3_background #7FB4CA

# The 16 terminal colors

# black
color0  #16161D
color8  #727169

# red
color1  #C34043
color9  #E82424

# green
color2  #76946A
color10 #98BB6C

# yellow
color3  #C0A36E
color11 #E6C384

# blue
color4  #7E9CD8
color12 #7FB4CA

# magenta
color5  #957FB8
color13 #938AA9

# cyan
color6  #6A9589
color14 #7AA89F

# white
color7  #C8C093
color15 #DCD7BA

# Extended colors
color16 #FFA066
color17 #FF5D62

