# ========== FONT ==========
font_family FiraCode Nerd Font
font_weight bold
font_size 13
text_composition_strategy platform
modify_font cell_height 140%

# ========== TRANSPARENCY ==========
background_opacity 0.91
 background_blur 0
 transparent_background_colors #43242B@0.8 #343A55@0.8 #002B36@0.95 #211d3d@0.8 #002B36@0.8

# ========== CURSOR ==========
cursor_shape block
cursor_blink_interval 0.6

# ========== BEHAVIOR ==========
enable_ligatures yes
visual_bell yes
enable_mouse_reporting yes
placement_strategy center
shell_integration enabled
detect_urls yes
url_style curly
scrollback_lines 10000

# ========== WINDOW PADDING ==========
window_padding_width 4 4 2 4
window_margin_width 0
window_border_width 0
draw_minimal_borders no
# active_border_color #000000

# ========== PERFORMANCE ==========
input_delay 0
repaint_delay 5
sync_to_monitor no

# ========== TAB BAR ==========
tab_bar_edge bottom
tab_bar_align left
tab_separator " "
tab_bar_style custom
tab_bar_margin_height 8.0 1.0
tab_bar_margin_width 5
tab_bar_min_tabs 1

# ========== INCLUDE THEME ==========
include proxysoul-water.conf

# ========== MACOS ==========
confirm_os_window_close -1
macos_quit_when_last_window_closed yes
hide_window_decorations titlebar-only
macos_option_as_alt no
macos_colorspace displayp3
