# vim:ft=kitty
## name: proxySoul
## author: proxySoul
## Deep purple with hot pink accents

# The basic colors
foreground              #e7e7ee
background              #020204
selection_foreground    #020204
selection_background    #7844f0

# Cursor colors
cursor                  #7844f0
cursor_text_color       #020204

# URL color when hovering with mouse
url_color               #9b6af5

# Kitty window border colors
active_border_color     #7844f0
inactive_border_color   #211e33
bell_border_color       #ff0059

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #020204
active_tab_background   #7844f0
inactive_tab_foreground #8e8ca1
inactive_tab_background #120e22
tab_bar_background      #020204

# Colors for marks
mark1_foreground #020204
mark1_background #7844f0
mark2_foreground #020204
mark2_background #ff0059
mark3_foreground #020204
mark3_background #9b6af5

# The 16 terminal colors

# black
color0 #1a1830
color8 #3d3b50

# red
color1 #ee0b2a
color9 #ff0059

# green
color2  #0b8b00
color10 #0b8b00

# yellow
color3  #de7c00
color11 #e65f2a

# blue
color4  #00a2ce
color12 #3bb8d8

# magenta
color5  #7844f0
color13 #9b6af5

# cyan
color6  #009a8b
color14 #009a8b

# white
color7  #8e8ca1
color15 #e7e7ee
