# vim:ft=kitty
## name: proxySoul Water
## author: proxySoul

# The basic colors
foreground              #e7e7ee
background              #020204
selection_foreground    #020204
selection_background    #00a2ce

# Cursor colors
cursor                  #00a2ce
cursor_text_color       #020204

# URL color when hovering with mouse
url_color               #3bb8d8

# Kitty window border colors
active_border_color     #00a2ce
inactive_border_color   #0e2030
bell_border_color       #de7c00

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #020204
active_tab_background   #00a2ce
inactive_tab_foreground #8e8ca1
inactive_tab_background #0e2030
tab_bar_background      #020204

# Colors for marks
mark1_foreground #020204
mark1_background #00a2ce
mark2_foreground #020204
mark2_background #009a8b
mark3_foreground #020204
mark3_background #3bb8d8

# The 16 terminal colors

# black
color0 #1a1830
color8 #3d3b50

# red
color1 #ee0b2a
color9 #ff0059

# green
color2  #0b8b00
color10 #0b8b00

# yellow
color3  #de7c00
color11 #de7c00

# blue
color4  #00a2ce
color12 #3bb8d8

# magenta
color5  #7844f0
color13 #9b6af5

# cyan
color6  #009a8b
color14 #009a8b

# white
color7  #8e8ca1
color15 #e7e7ee
