#!/bin/bash

options=(
  style=round
  hidpi=on
  borders
  "active_color=gradient(top_left=0xffc77dff,bottom_right=0xff9b5de5)"
  "inactive_color=gradient(top_left=0x884d4c7d,bottom_right=0x884d2d75)"
  width=6
)

# borders "${options[@]}"
