return {}
-- return {
--   "folke/sidekick.nvim",
--   enabled = true,
--   lazy = false,
--   opts = {
--     nes = {
--       enabled = function(buf)
--         return false
--         -- return vim.g.sidekick_nes ~= false and vim.b.sidekick_nes ~= false
--       end,
--     },
--   },
-- }
